[tools]
dprint = "latest"
typos = "latest"
actionlint = "latest"
zizmor = "latest"

[tasks.setup]
hide = true
confirm = "⚠️ This command will alter your system. Continue?"
description = "Setup the project"
depends = ["hooks"]

[tasks.audit]
# Extras, deep, thorough checks. Should be run locally.
hide = true
description = "Exhaustive quality check"
depends = ["check", "audit:*"]

[tasks.fix]
# Apply automatic fixes, then check.
# Intended for use before commit or push.
description = "Enforce rules"
depends = ["update-emacs-version", "fmt", "lint"]

[tasks.check]
# Quality check. Primarily used in CI.
hide = true
description = "Quality check"
depends = ["lint"]

[tasks.fmt]
hide = true
description = "Format"
run = "dprint fmt"

[tasks.lint]
# Minimal, fast feedback checks.
hide = true
description = "Lint"
run = [
  # format
  "dprint check",
  # typos
  "typos",
]

[tasks."audit:extras"]
hide = true
interactive = true
description = "Dependency analysis"
run = [
  # Dependencies
  "pnpx actions-up",
  # GitHub CI
  "actionlint",
  "zizmor .github/workflows/*",
]
