;; -*- coding: utf-8 -*-
(defconst fira-code--data
  '(["space.frac" " " "\xe100"]  ;   
    ["exclam.spacer" "!" "\xe101"]  ;   
    ["exclam_exclam.liga" "!!" "\xe102"]  ;   
    ["exclam_exclam_period.liga" "!!." "\xe103"]  ;   
    ["exclam_equal.liga" "!=" "\xe104"]  ;   
    ["exclam_equal.ss08" "!=" "\xe105"]  ;   
    ["exclam_equal_equal.liga" "!==" "\xe106"]  ;   
    ["exclam_equal_equal.ss08" "!==" "\xe107"]  ;   
    ["exclam_asciitilde.ss07" "!~" "\xe108"]  ;   
    ["numbersign.spacer" "#" "\xe109"]  ;   
    ["numbersign_exclam.liga" "#!" "\xe10a"]  ;   
    ["numbersign_parenleft.liga" "#(" "\xe10b"]  ;   
    ["numbersign_colon.liga" "#:" "\xe10c"]  ;   
    ["numbersign_colon.liga_rem" "#:" "\xe10d"]  ;   
    ["numbersign_equal.liga" "#=" "\xe10e"]  ;   
    ["numbersign_question.liga" "#?" "\xe10f"]  ;   
    ["numbersign_bracketleft.liga" "#[" "\xe110"]  ;   
    ["numbersign_underscore.liga" "#_" "\xe111"]  ;   
    ["numbersign_underscore_parenleft.liga" "#_(" "\xe112"]  ;   
    ["numbersign_braceleft.liga" "#{" "\xe113"]  ;   
    ["dollar.spacer" "$" "\xe114"]  ;   
    ["dollar.ss04" "$" "\xe115"]  ;   
    ["dollar_greater.liga" "$>" "\xe116"]  ;   
    ["dollar_greater.liga.ss04" "$>" "\xe117"]  ;   
    ["percent.spacer" "%" "\xe118"]  ;   
    ["percent_percent.liga" "%%" "\xe119"]  ;   
    ["ampersand.before.ss03" "&" "\xe11a"]  ;   
    ["ampersand.spacer" "&" "\xe11b"]  ;   
    ["ampersand.ss03" "&" "\xe11c"]  ;   
    ["ampersand_ampersand.liga" "&&" "\xe11d"]  ;   
    ["parenleft.case" "(" "\xe11e"]  ;   
    ["parenleft.dnom" "(" "\xe11f"]  ;   
    ["parenleft.numr" "(" "\xe120"]  ;   
    ["parenleft.spacer" "(" "\xe121"]  ;   
    ["parenright.case" ")" "\xe122"]  ;   
    ["parenright.dnom" ")" "\xe123"]  ;   
    ["parenright.numr" ")" "\xe124"]  ;   
    ["asterisk.lc" "*" "\xe125"]  ;   
    ["asterisk.spacer" "*" "\xe126"]  ;   
    ["asterisk_asterisk.liga" "**" "\xe127"]  ;   
    ["asterisk_asterisk_asterisk.liga" "***" "\xe128"]  ;   
    ["asterisk_slash.liga" "*/" "\xe129"]  ;   
    ["asterisk_greater.liga" "*>" "\xe12a"]  ;   
    ["plus.dnom" "+" "\xe12b"]  ;   
    ["plus.lc" "+" "\xe12c"]  ;   
    ["plus.numr" "+" "\xe12d"]  ;   
    ["plus.spacer" "+" "\xe12e"]  ;   
    ["plus_plus.liga" "++" "\xe12f"]  ;   
    ["plus_plus_plus.liga" "+++" "\xe130"]  ;   
    ["plus_greater.liga" "+>" "\xe131"]  ;   
    ["hyphen.case" "-" "\xe132"]  ;   
    ["hyphen.lc" "-" "\xe133"]  ;   
    ["hyphen.spacer" "-" "\xe134"]  ;   
    ["hyphen_hyphen.liga" "--" "\xe135"]  ;   
    ["hyphen_hyphen_hyphen.liga" "---" "\xe136"]  ;   
    ["hyphen_asciitilde.liga" "-~" "\xe137"]  ;   
    ["period.spacer" "." "\xe138"]  ;   
    ["period_hyphen.liga" ".-" "\xe139"]  ;   
    ["period_period.liga" ".." "\xe13a"]  ;   
    ["period_period_period.liga" "..." "\xe13b"]  ;   
    ["period_period_less.liga" "..<" "\xe13c"]  ;   
    ["period_period_equal.liga" "..=" "\xe13d"]  ;   
    ["period_equal.liga" ".=" "\xe13e"]  ;   
    ["period_question.liga" ".?" "\xe13f"]  ;   
    ["slash.spacer" "/" "\xe140"]  ;   
    ["slash_asterisk.liga" "/*" "\xe141"]  ;   
    ["slash_slash.liga" "//" "\xe142"]  ;   
    ["slash_slash_slash.liga" "///" "\xe143"]  ;   
    ["slash_greater.liga" "/>" "\xe144"]  ;   
    ["slash_backslash.liga" "/\\" "\xe145"]  ;   
    ["zero.dnom" "0" "\xe146"]  ;   
    ["zero.numr" "0" "\xe147"]  ;   
    ["zero.tosf" "0" "\xe148"]  ;   
    ["zero.tosf.zero" "0" "\xe149"]  ;   
    ["zero.zero" "0" "\xe14a"]  ;   
    ["zero.zero.tosf" "0" "\xe14b"]  ;   
    ["one.dnom" "1" "\xe14c"]  ;   
    ["one.numr" "1" "\xe14d"]  ;   
    ["one.tosf" "1" "\xe14e"]  ;   
    ["two.dnom" "2" "\xe14f"]  ;   
    ["two.numr" "2" "\xe150"]  ;   
    ["two.tosf" "2" "\xe151"]  ;   
    ["three.dnom" "3" "\xe152"]  ;   
    ["three.numr" "3" "\xe153"]  ;   
    ["three.tosf" "3" "\xe154"]  ;   
    ["four.dnom" "4" "\xe155"]  ;   
    ["four.numr" "4" "\xe156"]  ;   
    ["four.tosf" "4" "\xe157"]  ;   
    ["five.dnom" "5" "\xe158"]  ;   
    ["five.numr" "5" "\xe159"]  ;   
    ["five.tosf" "5" "\xe15a"]  ;   
    ["six.dnom" "6" "\xe15b"]  ;   
    ["six.numr" "6" "\xe15c"]  ;   
    ["six.tosf" "6" "\xe15d"]  ;   
    ["seven.dnom" "7" "\xe15e"]  ;   
    ["seven.numr" "7" "\xe15f"]  ;   
    ["seven.tosf" "7" "\xe160"]  ;   
    ["eight.dnom" "8" "\xe161"]  ;   
    ["eight.numr" "8" "\xe162"]  ;   
    ["eight.tosf" "8" "\xe163"]  ;   
    ["nine.dnom" "9" "\xe164"]  ;   
    ["nine.numr" "9" "\xe165"]  ;   
    ["nine.tosf" "9" "\xe166"]  ;   
    ["colon.center" ":" "\xe167"]  ;   
    ["colon.spacer" ":" "\xe168"]  ;   
    ["colon.uc" ":" "\xe169"]  ;   
    ["colon_colon.liga" "::" "\xe16a"]  ;   
    ["colon_colon_colon.liga" ":::" "\xe16b"]  ;   
    ["colon_colon_equal.liga" "::=" "\xe16c"]  ;   
    ["colon_equal.liga" ":=" "\xe16d"]  ;   
    ["semicolon.spacer" ";" "\xe16e"]  ;   
    ["semicolon_semicolon.liga" ";;" "\xe16f"]  ;   
    ["less.center" "<" "\xe170"]  ;   
    ["less.spacer" "<" "\xe171"]  ;   
    ["less_exclam_hyphen_hyphen.liga" "<!--" "\xe172"]  ;   
    ["less_dollar.liga" "<$" "\xe173"]  ;   
    ["less_dollar.liga.ss04" "<$" "\xe174"]  ;   
    ["less_dollar_greater.liga" "<$>" "\xe175"]  ;   
    ["less_dollar_greater.liga.ss04" "<$>" "\xe176"]  ;   
    ["less_asterisk.liga" "<*" "\xe177"]  ;   
    ["less_asterisk_greater.liga" "<*>" "\xe178"]  ;   
    ["less_plus.liga" "<+" "\xe179"]  ;   
    ["less_plus_greater.liga" "<+>" "\xe17a"]  ;   
    ["less_slash.liga" "</" "\xe17b"]  ;   
    ["less_slash_greater.liga" "</>" "\xe17c"]  ;   
    ["less_less.liga" "<<" "\xe17d"]  ;   
    ["less_less_less.liga" "<<<" "\xe17e"]  ;   
    ["less_equal.liga" "<=" "\xe17f"]  ;   
    ["less_equal.ss02" "<=" "\xe180"]  ;   
    ["less_greater.liga" "<>" "\xe181"]  ;   
    ["less_bar.liga" "<|" "\xe182"]  ;   
    ["less_bar_greater.liga" "<|>" "\xe183"]  ;   
    ["less_bar_bar.liga" "<||" "\xe184"]  ;   
    ["less_bar_bar_bar.liga" "<|||" "\xe185"]  ;   
    ["less_asciitilde.liga" "<~" "\xe186"]  ;   
    ["less_asciitilde_greater.liga" "<~>" "\xe187"]  ;   
    ["less_asciitilde_asciitilde.liga" "<~~" "\xe188"]  ;   
    ["equal.dnom" "=" "\xe189"]  ;   
    ["equal.numr" "=" "\xe18a"]  ;   
    ["equal.spacer" "=" "\xe18b"]  ;   
    ["equal_equal.liga" "==" "\xe18c"]  ;   
    ["equal_equal.ss08" "==" "\xe18d"]  ;   
    ["equal_equal_equal.liga" "===" "\xe18e"]  ;   
    ["equal_equal_equal.ss08" "===" "\xe18f"]  ;   
    ["equal_asciitilde.ss07" "=~" "\xe190"]  ;   
    ["greater.center" ">" "\xe191"]  ;   
    ["greater.spacer" ">" "\xe192"]  ;   
    ["greater_equal.liga" ">=" "\xe193"]  ;   
    ["greater_equal.ss02" ">=" "\xe194"]  ;   
    ["greater_greater.liga" ">>" "\xe195"]  ;   
    ["greater_greater_greater.liga" ">>>" "\xe196"]  ;   
    ["question.spacer" "?" "\xe197"]  ;   
    ["question_period.liga" "?." "\xe198"]  ;   
    ["question_equal.liga" "?=" "\xe199"]  ;   
    ["question_question.liga" "??" "\xe19a"]  ;   
    ["at.spacer" "@" "\xe19b"]  ;   
    ["at.ss05" "@" "\xe19c"]  ;   
    ["F.spacer" "F" "\xe19d"]  ;   
    ["T.spacer" "T" "\xe19e"]  ;   
    ["bracketleft.case" "[" "\xe19f"]  ;   
    ["bracketleft.spacer" "[" "\xe1a0"]  ;   
    ["bracketleft_bar.liga" "[|" "\xe1a1"]  ;   
    ["backslash.spacer" "\\" "\xe1a2"]  ;   
    ["backslash.ss06" "\\" "\xe1a3"]  ;   
    ["backslash.thick.ss06" "\\" "\xe1a4"]  ;   
    ["backslash_slash.liga" "\\/" "\xe1a5"]  ;   
    ["bracketright.case" "]" "\xe1a6"]  ;   
    ["bracketright.spacer" "]" "\xe1a7"]  ;   
    ["bracketright_numbersign.liga" "]#" "\xe1a8"]  ;   
    ["asciicircum.spacer" "^" "\xe1a9"]  ;   
    ["asciicircum_equal.liga" "^=" "\xe1aa"]  ;   
    ["underscore.spacer" "_" "\xe1ab"]  ;   
    ["grave.case" "`" "\xe1ac"]  ;   
    ["f.spacer" "f" "\xe1ad"]  ;   
    ["i.loclTRK" "i" "\xe1ae"]  ;   
    ["i.salt_low" "i" "\xe1af"]  ;   
    ["j.salt_low" "j" "\xe1b0"]  ;   
    ["l.salt_low" "l" "\xe1b1"]  ;   
    ["l.spacer" "l" "\xe1b2"]  ;   
    ["r.ss01" "r" "\xe1b3"]  ;   
    ["w.spacer" "w" "\xe1b4"]  ;   
    ["w_w_w.liga" "www" "\xe1b5"]  ;   
    ["x.multiply" "x" "\xe1b6"]  ;   
    ["x.multiply.tosf" "x" "\xe1b7"]  ;   
    ["braceleft.case" "{" "\xe1b8"]  ;   
    ["braceleft.spacer" "{" "\xe1b9"]  ;   
    ["braceleft_bar.liga" "{|" "\xe1ba"]  ;   
    ["bar.spacer" "|" "\xe1bb"]  ;   
    ["bar_greater.liga" "|>" "\xe1bc"]  ;   
    ["bar_bracketright.liga" "|]" "\xe1bd"]  ;   
    ["bar_bar.liga" "||" "\xe1be"]  ;   
    ["bar_bar_greater.liga" "||>" "\xe1bf"]  ;   
    ["bar_bar_bar.liga" "|||" "\xe1c0"]  ;   
    ["bar_bar_bar_greater.liga" "|||>" "\xe1c1"]  ;   
    ["bar_braceright.liga" "|}" "\xe1c2"]  ;   
    ["braceright.case" "}" "\xe1c3"]  ;   
    ["braceright.spacer" "}" "\xe1c4"]  ;   
    ["asciitilde.spacer" "~" "\xe1c5"]  ;   
    ["asciitilde_hyphen.liga" "~-" "\xe1c6"]  ;   
    ["asciitilde_greater.liga" "~>" "\xe1c7"]  ;   
    ["asciitilde_at.liga" "~@" "\xe1c8"]  ;   
    ["asciitilde_asciitilde.liga" "~~" "\xe1c9"]  ;   
    ["asciitilde_asciitilde_greater.liga" "~~>" "\xe1ca"]  ;   
    ["exclamdown.case" "¡" "\xe1cb"]  ;   
    ["dieresis.case" "¨" "\xe1cc"]  ;   
    ["guillemotleft.case" "«" "\xe1cd"]  ;   
    ["uni00AD.case" "­" "\xe1ce"]  ;   
    ["macron.case" "¯" "\xe1cf"]  ;   
    ["acute.case" "´" "\xe1d0"]  ;   
    ["acute.case.loclPLK" "´" "\xe1d1"]  ;   
    ["acute.loclPLK" "´" "\xe1d2"]  ;   
    ["cedilla.case" "¸" "\xe1d3"]  ;   
    ["guillemotright.case" "»" "\xe1d4"]  ;   
    ["questiondown.case" "¿" "\xe1d5"]  ;   
    ["Oacute.loclPLK" "Ó" "\xe1d6"]  ;   
    ["oacute.loclPLK" "ó" "\xe1d7"]  ;   
    ["Cacute.loclPLK" "Ć" "\xe1d8"]  ;   
    ["cacute.loclPLK" "ć" "\xe1d9"]  ;   
    ["Nacute.loclPLK" "Ń" "\xe1da"]  ;   
    ["nacute.loclPLK" "ń" "\xe1db"]  ;   
    ["Sacute.loclPLK" "Ś" "\xe1dc"]  ;   
    ["sacute.loclPLK" "ś" "\xe1dd"]  ;   
    ["Zacute.loclPLK" "Ź" "\xe1de"]  ;   
    ["zacute.loclPLK" "ź" "\xe1df"]  ;   
    ["circumflex.case" "ˆ" "\xe1e0"]  ;   
    ["caron.alt" "ˇ" "\xe1e1"]  ;   
    ["caron.case" "ˇ" "\xe1e2"]  ;   
    ["breve.case" "˘" "\xe1e3"]  ;   
    ["dotaccent.case" "˙" "\xe1e4"]  ;   
    ["ring.case" "˚" "\xe1e5"]  ;   
    ["tilde.case" "˜" "\xe1e6"]  ;   
    ["hungarumlaut.case" "˝" "\xe1e7"]  ;   
    ["uni0326.case" "̦" "\xe1e8"]  ;   
    ["tonos.case" "΄" "\xe1e9"]  ;   
    ["uni1FEF.case" "`" "\xe1ea"]  ;   
    ["uni1FFD.case" "´" "\xe1eb"]  ;   
    ["uni2007.tf" " " "\xe1ec"]  ;   
    ["endash.case" "–" "\xe1ed"]  ;   
    ["emdash.case" "—" "\xe1ee"]  ;   
    ["guilsinglleft.case" "‹" "\xe1ef"]  ;   
    ["guilsinglright.case" "›" "\xe1f0"]  ;   
    ["minus.dnom" "−" "\xe1f1"]  ;   
    ["minus.numr" "−" "\xe1f2"]  ;   
    ["infinity.case" "∞" "\xe1f3"]  ;   
))
